server:
    adminMinThreads: 1
    adminMaxThreads: 64
    adminContextPath: /
    applicationContextPath: /
    applicationConnectors:
        - type: http
          port: 8080
    adminConnectors:
        - type: http
          port: 8081
database:
    url: jdbc:sqlserver://localhost:1433;databaseName=GeoLocation
    driverClass: com.microsoft.sqlserver.jdbc.SQLServerDriver
    user: sa
    password: NotToday@911

swaggerBasePath: http://localhost:9080